name: Flaky Test Detection

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Run Spotless Check
      run: mvn spotless:check

    - name: Build project
      run: mvn clean install -DskipTests -Djib.skip

    - name: Run the test
      run: mvn test -DfailIfNoTests=false -Dtest=com.google.cloud.teleport.bigtable.CassandraRowMapperFnTest#test
      
    - name: Run NonDex for flaky tests detection
      run: mvn edu.illinois:nondex-maven-plugin:2.1.1:nondex -DnondexRuns=10 -Dtest=com.google.cloud.teleport.bigtable.CassandraRowMapperFnTest#testMapFloatColumn -DfailIfNoTests=false    
     
